FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# hexgame

Hexgame is an API for managing and play hex board based games

## Games Collection [/games]

### List All Games [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Tanks",
                "author": "John Q. Public",
                "copyright": "2019"
            },
            {
                "name": "Ships",
                "author": "Some D. Uude",
                "copyright": "1987"
            }
        ]

### Create a New Game [POST]

You may create your own game using this action. It takes a JSON
object containing the name and other info.

+ Request (application/json)

        {
            "name" "Cars",
            "author": "Sue Mee",
            "copyright": "2014"
        }

+ Response 201 (application/json)

    + Headers

            Location: /games/1

    + Body

            {
                "name": "Cars",
                "author": "Sue Mee",
                "copyright": "2014"
            }