FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# HexGame Server

Hexgame is an API for managing and play hex board based games

# Group Game

---
**Game Attributes:** 

- id `(Number)` : unique identifier. 
- title `(String)` : The title of the game.
- author `(String)` : The person who wrote the game
- publisher `(String)` : The company that publishes the game
- copyright `(String)` : The copyright date of the game

---
## Games Collection [/games]
Retrieve a list of games

### List all games [GET]
+ Response 200 (application/json)

    + Header
    
            Location: https://mysite.com/games

    + Body
  
            [
                {
                    "id": 1,
                    "title": "Cave People",
                    "author": "Jean Auel"
                    "publisher": "Dell Books"
                    "copyright": "1983"
                },
                {
                    "id": 2,
                    "title": "Tanks",
                    "author": "R. Lee Ermey"
                    "publisher": "Discovery Channel"
                    "copyright": "2010"
                },
                {
                    "id": 3,
                    "title": "Cars",
                    "author": "Jeremy Clarkson"
                    "publisher": "Motor Trend"
                    "copyright": "2017"
                }
                {
                    "id": 4,
                    "title": "Ships",
                    "author": "C. S. Forrester"
                    "publisher": "Hornblower Books"
                    "copyright": "1953"
                }
            ]

## A Single Game [/games/{id}]
Manage single games

### Get a single game [GET]
Retrieve a single game

+ Response 200 (application/json)

    + Header

            Location: https://mysite.com/games/1

    + Body
    
            { 
                "id": 1,
                "title": "Cave People",
                "author": "Jean Auel"
                "publisher": "Dell Books"
                "copyright": "1983"
            }

# Group Map

---
## Maps Collection [/games/{id}/maps]
Retrieve a list of maps for a game

+ Response 200 (application/json)

    + Header

            Location: https://mysite.com/games/1/maps

    + Body

            [
                {
                    "id": 1,
                    "name": "Villiage",
                    "url": "https://mysite.com/games/1/maps/1"
                },
                {
                    "id": 2,
                    "name": "Water Hole",
                    "url": "https://mysite.com/games/1/maps/2"
                },
                {
                    "id": 3,
                    "name": "Hunting Ground",
                    "url": "https://mysite.com/games/1/maps/3"
                }
            ]
